Name: Arman Saini\
Roll No.: 102303676\
Group: 3C51\
Branch: COE

Note: Apologies for late submission.\
I have added comments trying to explain the code in a way I find easy to understand.

In [4]:
import numpy as np
#just importin numpy and then using it through this 'np' alias that we gave

In [3]:
arr = np.array([2, 9, 9, 7, 9, 2, 4, 5, 8])
# creating a numpy array from a Python list

print(arr)

[2 9 9 7 9 2 4 5 8]


In [6]:
rarr = arr[::-1]
print(rarr)
# slicing trick to reverse the array
# [start:end:step] → step = -1 means go backwards

[8 5 4 2 9 7 9 9 2]


In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
# creating two 2D arrays (basically matrices)

print(arr1 == arr2)
# element-wise comparison
# compares each position and returns True/False
# not checking if whole arrays are equal, but each element

[[ True  True  True]
 [ True  True  True]]


In [10]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])
# two arrays with repeated values

mfreq_x = np.argmax(np.bincount(x))
# bincount → counts frequency of each number
# argmax → index of the highest frequency
# so this gives most frequent number in x

mfreq_y = np.argmax(np.bincount(y))
# same idea for y

print(mfreq_x, mfreq_y)
# prints most frequent elements
# output: 1 1

1 1


In [12]:
anotherArray = np.matrix('[4,1,9;12,3,1;4,5,6]')
# creating a matrix using numpy's matrix class
# semicolons separate rows

print(anotherArray.sum(), '\n', anotherArray.sum(axis=1), '\n', anotherArray.sum(axis=0))
# anotherArray.sum() → sum of all elements
# axis=1 → row-wise sum
# axis=0 → column-wise sum

45 
 [[14]
 [16]
 [15]] 
 [[20  9 16]]
